### ISSUE TITLE
Static compiler compile diffutils-3.3 errors

### ISSUE THREAD

**Issue by houzi-** [lancethepants/tomatoware#17]
```
./configure --prefix=/mmc/diff --enable-static
```
ERRO:
```
dcigettext.c:(.text+0x7e4): undefined reference to `libiconv'
dcigettext.c:(.text+0x9d4): undefined reference to `libiconv_open'
dcigettext.c:(.text+0xb0c): undefined reference to `libiconv_open'
/mmc/lib/gcc/arm-buildroot-linux-uclibcgnueabi/5.2.0/../../../libintl.a(relocatable.o): In function `libintl_set_relocation_prefix':
relocatable.c:(.text+0x44): undefined reference to `libiconv_set_relocation_prefix'
collect2: error: ld returned 1 exit status
Makefile:1222: recipe for target 'cmp' failed
make[2]: *** [cmp] Error 1
```
Compile reason:
I would like to statically compiled diffutils-3.3 so I can quickly mounted to the platform above the other , and tomatoware is built dynamically compiled libraries must rely on to run tomatoware

**Comment by lancethepants** [comment]
Always try with LDFLAGS first.

LDFLAGS="-Wl,-static -static -static-libgcc -static-libstdc++" ./configure --prefix=/mmc/diff
make

**Comment by houzi-** [comment]
This compiler parameters originally tried! Or dynamic compiler version

**Comment by houzi-** [comment]
This parameter is compiled here are dynamic version

**Comment by lancethepants** [comment]
Sorry, I'm not sure I understand.

I was able to compile diffutils on the router so that it is static using the configure options I previously posted.

**Comment by houzi-** [comment]
it can not be! You can use this parameter compiler to compile a static version? I used the latest tomatoware, but should be okay with this!

**Comment by rampageX** [comment]
just use @lancethepants way:

$ file ./src/diff3
./src/diff3: ELF 32-bit LSB executable, ARM, version 1 (SYSV), statically linked, not stripped

**Comment by houzi-** [comment]
@rampageX @rampageX 
Thank you very much! Some of the problems I have compiled tomatoware, due to the parameters can not be correctly transferred into @lance tools can be . I previously is compiled using the parameters of thought is to compile parameters are incorrect. Ha ha ha
