### ISSUE TITLE
Time lags behind in Asteriek logs 3 hours

### ISSUE THREAD

**Issue by sergeynr** [lancethepants/tomatoware#20]
Hello! Time lags behind in Asteriek notice logs 3 hours. System time GMT-3 - Mowcow correct. Command "!date" in Asterisk console correct. But time in logs Asterisk incorrect.

**Comment by lancethepants** [comment]
This post addresses how to get the correct time in the logs.

http://www.linksysinfo.org/index.php?threads/asterisk-google-voice-tomatousb-the-easy-way.68813/#post-241851

**Comment by sergeynr** [comment]
Thanks

**Comment by lancethepants** [comment]
That should take care of it. Post back here if you run into any issues.
