### ISSUE TITLE
GO mipsel compiler problem

### ISSUE THREAD

**Issue by houzi-** [lancethepants/tomatoware#22]
Don't know whether mipsel support go program compilation, feel the kernel version should be too low? Do not know if you have any good suggestions?

**Comment by lancethepants** [comment]
http://linksysinfo.org/index.php?threads/tomatoware.69742/page-3#post-270447

This explains some reason for no Go in mips. I've read that maybe Go 1.6 might support mips, so we'll see if that happens.

**Comment by houzi-** [comment]
Wow! look forward to!
