### ISSUE TITLE
 tomatoware-mipsel compiler dnsmasq-2.75 run-time errors generated binaries

### ISSUE THREAD

**Issue by houzi-** [lancethepants/tomatoware#28]
hello! lance 

tomatoware-mipsel compiled dnsmasq-2.75 generated binary fail
ERROR:
```
dnsmasq: failed to create inotify: Function not implemented
```
arm compiled binary file is not the case

**Comment by lancethepants** [comment]
http://lists.thekelleys.org.uk/pipermail/dnsmasq-discuss/2015q2/009644.html

`make COPTS=-DNO_INOTIFY`

**Comment by houzi-** [comment]
Thanks! solved
