### ISSUE TITLE
ARM release version

### ISSUE THREAD

**Issue by EionRobb** [lancethepants/tomatoware#3]
Hi there,

Wanting to use tomatoware on my Tomato R7000, however it's ARM-based, not MIPS. 
Any chance of a pre-compiled ARM version of tomatoware?

**Comment by lancethepants** [comment]
I've made another arm release, v1.0.1.  This uses a totally different toolchain made from buildroot.  It uses the latest versions of uclibc and gcc. Everything else is the same to the mipsel version.

It's been working very well for me, and think it will for you as well.

I'll give some time for feedback and will then close this, as I think arm is now good to roll.

**Comment by lancethepants** [comment]
More info regarding Tomatoware and ARM.
http://www.linksysinfo.org/index.php?threads/tomatoware.69742/page-3#post-258168

Been running well for me so far.
