### ISSUE TITLE
 I do not know whether clang on to build tomatoware

### ISSUE THREAD

**Issue by houzi-** [lancethepants/tomatoware#35]
With the above title

**Comment by lancethepants** [comment]
I cross-compile tomatoware with Debian, which uses gcc.  Tomatoware itself also uses gcc.  I once experimented with clang and got it working in Tomatoware.  I did manage to compile c and c++ applications with it, but I had lots of hacks to do it.  It would need some patching to make it as seamless as gcc, so it hasn't been included.

**Comment by lancethepants** [comment]
Hopefully the above has answered your question. Comment again if it doesn't.  Over 1 month without response so closing.
