### ISSUE TITLE
Question about base.sh

### ISSUE THREAD

**Issue by someburner** [lancethepants/tomatoware#41]
#https://github.com/lancethepants/tomatoware/blob/f4f8b0b3f1dc9e437c54d767e892fb3ffe7a89ba/scripts/base.sh#L1000

^ is this intended? (the `rm -rf` and also the `=` after VERSION?

Also, a general question: what is asterisk used for exactly? I spent some time on their website, but it left me pretty clueless still. Is it just for VoIP or..?

**Comment by lancethepants** [comment]
Nope, not intended. Thanks for pointing this out.  Didn't seem to break things, but shouldn't be there. Fixed in f5f415f5d16f85399a351f53e415012bb497d1de
