### ISSUE TITLE
allow-prefer-chacha20.patch

### ISSUE THREAD

**Issue by rampageX** [lancethepants/tomatoware#46]
Most router have no AES support, can we do this patch also?

https://github.com/trojan-gfw/openwrt-trojan/blob/master/openssl1.1/patches/1.1.1/140-allow-prefer-chacha20.patch

**Comment by lancethepants** [comment]
Added in commit bbc3849e3104072d51af0d2c5fc33228230e3164

Taken from openwrt
https://github.com/openwrt/openwrt/blob/master/package/libs/openssl/patches/140-allow-prefer-chacha20.patch
