### ISSUE TITLE
[Question] Update kernel version 3.10 + for armv7

### ISSUE THREAD

**Issue by 0neday** [lancethepants/tomatoware#47]

**Comment by lancethepants** [comment]
Tomatoware tracks the kernel found in Tomato firmware, 2.6.36.4. Unfortunately tomato that runs on armv7 will probably never be able to upgrade to anything else. We'll see if tomato gets ported to aarch64, which undoubtedly would run a newer kernel version.
Of course if you're running a different firmware like dd-wrt with a newer kernel, binaries compiled using Tomatoware and it's older kernel should run without any issues on systems with newer kernels.
