### ISSUE TITLE
Don't require building mips toolchain as a prerequisite to building ARM?

### ISSUE THREAD

**Issue by HunterZ** [lancethepants/tomatoware#48]
I recently upgraded to an ARM router and decided to rebuild latest Tomatoware from scratch in my Debian VM, and smacked into an error stating that building ARM requires first building a toolchain in mips mode. This seems bizarre!

**Comment by HunterZ** [comment]
Thanks, that suggestion gets me past the error.

I'll leave this issue open as a reminder to change the error message.

**Comment by lancethepants** [comment]
Documented now in c4071f1a9e1b6e6ea1d214dbecdad32b23ac4f0d
