### ISSUE TITLE
Asterisk CDR MySQL

### ISSUE THREAD

**Issue by sergeynr** [lancethepants/tomatoware#6]
Hello! Only SQLite can be used? There is a support of mysql? There is no module cdr_mysql.so

**Comment by lancethepants** [comment]
cdr_mysql.so is now included in tomatoware v1.0. I haven't tested the feature myself, so feedback welcome.

**Comment by sergeynr** [comment]
Thank you. But I have Asus RT-AC68U. Processor ARM. Еhere is a version 1.0 for ARM?

**Comment by sergeynr** [comment]
There is a version 1.0 for ARM?

**Comment by lancethepants** [comment]
I'll compile one up. I wasn't aware anyone was using the ARM build, I haven't received any feedback on it. There are certain parts of it that are broken. Sometime I'll get around to addressing those. Asterisk however has been working fine for arm?

**Comment by sergeynr** [comment]
Yes, of course. Thanks a lot.

**Comment by lancethepants** [comment]
Arm available here.
http://files.lancethepants.com/Tomatoware/

**Comment by sergeynr** [comment]
Thanks

**Comment by lancethepants** [comment]
Is this feature working fine?
