### ISSUE TITLE
Error unexpected word (expecting ")")

### ISSUE THREAD

**Issue by sergeynr** [lancethepants/tomatoware#7]
Hello! Router Asus RT-AC86U. Rep: mipsel-soft-jffs. Eror: /jffs/sbin/asterisk: line 2: syntax error: unexpected word (expecting ")")

**Comment by lancethepants** [comment]
The RT-68U(?) is an ARM router, so the mipsel images will not work on it. I currently have an ARM image, only available at the following link, that is still experimental that you can try.
http://files.lancethepants.com/Tomatoware/

The directory labeled "v0.9.5+ Arm Experimental".

**Comment by sergeynr** [comment]
Thank you!
